/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.13/samples
 */

repositories {
    google()
    mavenCentral()
}

// Dependencies removed as they should be in the app-level build.gradle file
